export const webPlans = [
  {
    planName: "Basic Plan",
    price: "7,999",
    features: [
      "5 pages Website",
      "1 Year Free Domain Name (.com .in .org)",
      "1 Year Free Hosting (Unlimited Space)",
      "Dynamic Website (Premium Design)",
      "Admin Access",
      "Lifetime 24/7 Free Hosting Support",
      "Unlimited Images & Videos Upload",
      "Free SSL Certificates",
      "5 Free Email Id",
      "SEO Friendly Website",
      "100% Responsive Website",
      "Live Chat Integration",
      "Payment Gateway Integration",
      "Social Media Integration",
      "Call Button Integration",
      "WhatsApp Button Integration",
      "Inquiry Form",
    ],
  },
  {
    planName: "Standard Plan",
    price: "14,999",
    features: [
      "10 pages Website",
      "1 Year Free Domain Name (.com .in .org)",
      "1 Year Free Hosting (Unlimited Space)",
      "Dynamic Website (Premium Design)",
      "Admin Access",
      "Lifetime 24/7 Free Hosting Support",
      "Unlimited Images & Videos Upload",
      "Free SSL Certificates",
      "10 Free Email Id",
      "SEO Friendly Website",
      "100% Responsive Website",
      "Live Chat Integration",
      "Payment Gateway Integration",
      "Social Media Integration",
      "Call Button Integration",
      "WhatsApp Button Integration",
      "Inquiry Form",
    ],
  },
  {
    planName: "Premium Plan",
    price: "25,999",
    features: [
      "15 pages Website",
      "1 Year Free Domain Name (.com .in .org)",
      "1 Year Free Hosting (Unlimited Space)",
      "Dynamic Website (Premium Design)",
      "Admin Access",
      "Lifetime 24/7 Free Hosting Support",
      "Unlimited Images & Videos Upload",
      "Free SSL Certificates",
      "15 Free Email Id",
      "SEO Friendly Website",
      "100% Responsive Website",
      "Live Chat Integration",
      "Payment Gateway Integration",
      "Social Media Integration",
      "Call Button Integration",
      "WhatsApp Button Integration",
      "Inquiry Form",
    ],
  },
];

// You can do the same for software & marketing plans
export const DigitalPlans = [
  {
    planName: "Basic Plan",
    price: "999",
    features: [
      "Logo Design",
      "Business Card Design",
      "Content Creation",
      "2 Degital Business Brochure ",
      "7 Social Media Posters",
    ],
  },
  {
    planName: "Standard Plan",
    price: "2,999",
    features: [
      "Logo Design",
      "Business Card Design",
      "Content Creation",
      "2 Degital Business Brochure ",
      "10 Social Media Posters",
      "2 Social Media Videos For Business Marketing",
    ],
  },
  {
    planName: "Premium Plan",
    price: "4,999",
    features: [
      "Logo Design",
      "Business Card Design",
      "Content Creation",
      "2 Flyer Design",
      "5 Degital Business Brochure ",
      "15 Social Media Posters",
      "5 Social Media Videos For Business Marketing",
    ],
  },
];

export const SoftwarePlans = [
  {
    planName: "Startup Boost",
    price: "4,999",
    features: [
      "SEO Optimization",
      "1 Month Content Plan",
      "Google My Business Setup",
      "Instagram + Facebook Setup",
      "Weekly Reports",
    ],
  },
  {
    planName: "Growth Campaign",
    price: "9,999",
    features: [
      "Weekly Content Posting",
      "Lead Gen Ads",
      "SEO + SMM Strategy",
      "Email Campaigns",
      "Monthly Analytics",
    ],
  },
  {
    planName: "Full Service Marketing",
    price: "18,999",
    features: [
      "Complete Digital Presence",
      "Google Ads + Meta Ads",
      "Blog + Email Content",
      "Conversion Optimization",
      "CRM Integration",
    ],
  },
];
